# Generated by Django 4.1.4 on 2024-10-18 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_alter_answer_downvoters_alter_answer_upvoters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
