# Generated by Django 5.1.2 on 2024-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_downvoters_alter_answer_upvoters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='questions.tag'),
        ),
    ]
